version: '3.9'
services:
  rabbitmq:
    hostname: my-rabbit
    container_name: rabbitmq
    image: rabbitmq:3.11-management-delayed_message_exchange
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "15672:15672"
      - "5672:5672"
      - "25676:25676"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
volumes:
  rabbitmq_data: