#Executar docker-compose up -d
#Acessar localhost:5050
#usuário e senha vide yaml pgadmin4_container
#
#Criar nova conexão no pgadmin
#Pegar IP do banco: 
#docker inspect <hash_container_bd> | grep IPAddress
#usuário e senha vide yaml pg_container

version: '3.9'
services:
  db:
    container_name: pg_container
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:6
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
