#conf wsl
#wsl -d docker-desktop
#sysctl -w vm.max_map_count=262144
#-Delastic.apm.service_name=juvo -Delastic.apm.server_url=http://localhost:8200 -Delastic.apm.application_packages=* -javaagent:C:\Desenvolvimento\maven-repo\elastic-apm-agent-1.18.0.RC1.jar 

# Executar via docker-compose
#docker-compose up -d

#Executar via docker swarm
#docker swarm init
#docker stack deploy -c docker-compose.yml elastic-apm
version: '3.9'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
    environment:
      - "http.host=0.0.0.0"
      - "transport.host=127.0.0.1"
      - "ES_JAVA_OPTS=-Xmx512m -Xms512m"
      - "ELASTIC_PASSWORD=changeme"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.2
    ports:
      - 5601:5601
    networks:
      - elk
    depends_on:
      - elasticsearch

  apm-server:
    image: docker.elastic.co/apm/apm-server:7.13.1
    ports:
      - 8200:8200
    networks:
      - elk
    depends_on:
      - elasticsearch

volumes:
  esdata:

networks:
  elk:
